autobump = "patch"

[registries.cratebox]
cargo_name = "cratebox"
confirm = false

[registries.crates-io]
confirm = true

[pipelines.default]
stages = ["cratebox", "crates-io"]

[pipeline]
stages = ["development", "testing", "staging", "production"]
release_branch = "production"
