use std::path::PathBuf;

use serde::Deserialize;

use crate::domain::{Preset, ProjectSpec};

#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FileEntry {
    pub path: PathBuf,
    pub contents: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
struct ScaffoldDefinition {
    preset: String,
    files: Vec<ScaffoldFileDefinition>,
}

#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
struct ScaffoldFileDefinition {
    path: PathBuf,
    contents: String,
}

#[non_exhaustive]
#[derive(Debug)]
pub enum ScaffoldError {
    Yaml(String),
    PresetMismatch {
        expected: &'static str,
        actual: String,
    },
}

pub fn generate(spec: &ProjectSpec) -> Result<Vec<FileEntry>, ScaffoldError> {
    let definition = definition_for(spec.preset)?;
    generate_from_definition(spec, &definition)
}

fn definition_for(preset: Preset) -> Result<ScaffoldDefinition, ScaffoldError> {
    match preset {
        Preset::RustCli => definition_from_yaml(include_str!("../scaffolds/rust-cli.yaml")),
    }
}

fn definition_from_yaml(input: &str) -> Result<ScaffoldDefinition, ScaffoldError> {
    serde_yaml::from_str(input).map_err(|error| ScaffoldError::Yaml(error.to_string()))
}

fn generate_from_definition(
    spec: &ProjectSpec,
    definition: &ScaffoldDefinition,
) -> Result<Vec<FileEntry>, ScaffoldError> {
    let expected = spec.preset.as_str();
    if definition.preset != expected {
        return Err(ScaffoldError::PresetMismatch {
            expected,
            actual: definition.preset.clone(),
        });
    }

    let target = spec.target_dir();
    Ok(definition
        .files
        .iter()
        .map(|file| FileEntry {
            path: target.join(&file.path),
            contents: interpolate(&file.contents, spec),
        })
        .collect())
}

fn interpolate(template: &str, spec: &ProjectSpec) -> String {
    template
        .replace("{{name}}", &spec.name)
        .replace("{{description}}", &spec.description)
        .replace("{{preset}}", spec.preset.as_str())
}

impl std::fmt::Display for ScaffoldError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Yaml(message) => write!(formatter, "invalid scaffold YAML: {message}"),
            Self::PresetMismatch { expected, actual } => write!(
                formatter,
                "scaffold preset mismatch: expected `{expected}`, got `{actual}`"
            ),
        }
    }
}

impl std::error::Error for ScaffoldError {}

#[cfg(test)]
mod tests {
    use std::path::Path;

    use super::*;

    const SAMPLE_DEFINITION: &str = r#"
preset: rust-cli
files:
  - path: README.md
    contents: |
      # {{name}}

      {{description}}
"#;

    fn spec() -> ProjectSpec {
        ProjectSpec::new(
            "spark-demo",
            "A demo CLI generated by sparkfile.",
            Preset::RustCli,
            "/tmp/dev",
        )
        .expect("valid spec")
    }

    #[test]
    fn parses_yaml_scaffold_definition() {
        let definition = definition_from_yaml(SAMPLE_DEFINITION).expect("valid YAML definition");

        assert_eq!(definition.preset, "rust-cli");
        assert_eq!(definition.files.len(), 1);
        assert_eq!(definition.files[0].path, Path::new("README.md"));
        assert!(definition.files[0].contents.contains("{{name}}"));
    }

    #[test]
    fn rust_cli_generates_expected_file_inventory() {
        let files = generate(&spec()).expect("scaffold should generate");
        let paths = files
            .iter()
            .map(|file| file.path.as_path())
            .collect::<Vec<_>>();

        assert_eq!(
            paths,
            vec![
                Path::new("/tmp/dev/spark-demo/Cargo.toml"),
                Path::new("/tmp/dev/spark-demo/src/main.rs"),
                Path::new("/tmp/dev/spark-demo/README.md"),
                Path::new("/tmp/dev/spark-demo/CLAUDE.md"),
                Path::new("/tmp/dev/spark-demo/Justfile"),
                Path::new("/tmp/dev/spark-demo/.gitignore"),
                Path::new("/tmp/dev/spark-demo/.ctx/HANDOFF.yaml"),
            ]
        );
    }

    #[test]
    fn generated_content_includes_project_name_and_description() {
        let files = generate(&spec()).expect("scaffold should generate");
        let readme = files
            .iter()
            .find(|file| file.path.ends_with("README.md"))
            .expect("README should be generated");

        assert!(readme.contents.contains("# spark-demo"));
        assert!(
            readme
                .contents
                .contains("A demo CLI generated by sparkfile.")
        );
    }

    #[test]
    fn yaml_parse_error_returns_scaffold_error_yaml() {
        let result = definition_from_yaml("not: valid: yaml: [");
        assert!(
            matches!(result, Err(ScaffoldError::Yaml(_))),
            "expected Err(ScaffoldError::Yaml), got {result:?}"
        );
    }

    #[test]
    fn preset_mismatch_returns_error() {
        let wrong_preset_yaml = r#"
preset: wrong-preset
files:
  - path: README.md
    contents: hello
"#;
        let definition = definition_from_yaml(wrong_preset_yaml).expect("valid YAML");
        let result = generate_from_definition(&spec(), &definition);
        assert!(
            matches!(
                result,
                Err(ScaffoldError::PresetMismatch {
                    expected: "rust-cli",
                    actual: ref a,
                }) if a == "wrong-preset"
            ),
            "expected PresetMismatch error, got {result:?}"
        );
    }

    #[test]
    fn preset_placeholder_is_interpolated() {
        let yaml_with_preset = r#"
preset: rust-cli
files:
  - path: info.txt
    contents: "preset={{preset}}"
"#;
        let definition = definition_from_yaml(yaml_with_preset).expect("valid YAML");
        let files = generate_from_definition(&spec(), &definition).expect("should generate");
        assert_eq!(files[0].contents, "preset=rust-cli");
    }
}
